In [1]:
import numpy

In [4]:
n=numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [5]:
type(n)

numpy.ndarray

In [9]:
n.reshape(3, 9) #make it into a array of r x c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [13]:
n.reshape(3,3,3) #3x3 3times

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [14]:
#passing a normal py list into numpy array

In [16]:
my_list = [[1,2,3,4],[],[1, 3, 3, 4]]

m = numpy.asarray(my_list)
m

array([list([1, 2, 3, 4]), list([]), list([1, 3, 3, 4])], dtype=object)