In [1]:
import pandas #for reading file
import cv2
import numpy

In [6]:
img_gray = cv2.imread("smallgray.png",0)
img_gray


array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [8]:
img_rbg = cv2.imread("smallgray.png",1)
img_rbg


array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [9]:
img_java = cv2.imread("java full stack.PNG")
img_java

array([[[249, 249, 249],
        [249, 249, 249],
        [249, 249, 249],
        ...,
        [212, 200, 191],
        [249, 249, 249],
        [249, 249, 249]],

       [[249, 249, 249],
        [249, 249, 249],
        [249, 249, 249],
        ...,
        [212, 200, 191],
        [249, 249, 249],
        [249, 249, 249]],

       [[249, 249, 249],
        [249, 249, 249],
        [249, 249, 249],
        ...,
        [212, 200, 191],
        [249, 249, 249],
        [249, 249, 249]],

       ...,

       [[249, 249, 249],
        [249, 249, 249],
        [249, 249, 249],
        ...,
        [249, 249, 249],
        [249, 249, 249],
        [249, 249, 249]],

       [[249, 249, 249],
        [249, 249, 249],
        [249, 249, 249],
        ...,
        [249, 249, 249],
        [249, 249, 249],
        [249, 249, 249]],

       [[249, 249, 249],
        [249, 249, 249],
        [249, 249, 249],
        ...,
        [249, 249, 249],
        [249, 249, 249],
        [249, 249, 249]]

In [10]:
#...............Creating Image ..................

In [12]:
cv2.imwrite("myImage.png", img_java)


True