In [1]:
import numpy
import cv2

In [3]:
img_gray = cv2.imread('smallgray.png', 0)

In [4]:
img_gray

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [ ]:
##indexing .................................

In [5]:
img_gray[1][3] #get the number on second row col 4

255

In [6]:
img_gray[:2] #first 2 rows

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [15]:
img_gray[:2][1][1:4] #first two rows, second line, col 1 to 4 exclusive

array([125, 255, 255], dtype=uint8)

In [18]:
img_gray[0:2, 2:4] #first two rows and 1:4 col

array([[104, 121],
       [255, 255]], dtype=uint8)

In [19]:
img_gray.shape

(3, 5)

In [21]:
img_gray

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [22]:
#all 3 rows but first 3 col
img_gray[:, 0:3]

array([[187, 158, 104],
       [198, 125, 255],
       [209, 134, 255]], dtype=uint8)

In [23]:
#last two row col 2 to 4 inclusive
img_gray[1:, 1:5]

array([[125, 255, 255, 147],
       [134, 255,  97, 182]], dtype=uint8)

In [24]:
#iterating

In [36]:
for i in img_gray:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [26]:
for i in img_gray:
    for j in i:
        print(j) #print everything inline

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [37]:
#same as above
for i in img_gray.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [29]:
for i in img_gray.T:
    print(i) 

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [41]:
img_grayT = img_gray.T #making it a Transpose
for i in img_grayT.flat: #iterating and printing
    print(i)

187
198
209
158
125
134
104
255
255
121
255
97
143
147
182
