In [49]:
import numpy
import cv2

In [50]:
img_gray=cv2.imread('smallgray.png', 0)

In [51]:
img_gray

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [52]:
#stacking two arrays

myArray = [
    [1, 2, 3, 4, 5,],
    [2, 4, 6, 8, 10],
    [3, 6, 9, 12, 15]
]

In [53]:
#STACK OR JOIN TWO ARRAYS

In [64]:
joinedArrayH=numpy.hstack((myArray, img_gray)) #stack horizontally
joinedArrayH

array([[  1,   2,   3,   4,   5, 187, 158, 104, 121, 143],
       [  2,   4,   6,   8,  10, 198, 125, 255, 255, 147],
       [  3,   6,   9,  12,  15, 209, 134, 255,  97, 182]])

In [77]:
splitArrayH = numpy.hsplit(joinedArrayH, 2)
splitArrayH

[array([[ 1,  2,  3,  4,  5],
        [ 2,  4,  6,  8, 10],
        [ 3,  6,  9, 12, 15]]),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]])]

In [78]:
splitArrayH = numpy.hsplit(joinedArrayH, 5)
splitArrayH

[array([[1, 2],
        [2, 4],
        [3, 6]]),
 array([[ 3,  4],
        [ 6,  8],
        [ 9, 12]]),
 array([[  5, 187],
        [ 10, 198],
        [ 15, 209]]),
 array([[158, 104],
        [125, 255],
        [134, 255]]),
 array([[121, 143],
        [255, 147],
        [ 97, 182]])]

In [66]:
joinedArrayV=numpy.vstack((myArray, img_gray)) #stack vertically
joinedArrayV

array([[  1,   2,   3,   4,   5],
       [  2,   4,   6,   8,  10],
       [  3,   6,   9,  12,  15],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]])

In [84]:
splitArrayV = numpy.vsplit(joinedArrayV, 2)
splitArrayV

[array([[ 1,  2,  3,  4,  5],
        [ 2,  4,  6,  8, 10],
        [ 3,  6,  9, 12, 15]]),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]])]

In [85]:
splitArrayV = numpy.vsplit(joinedArrayV, 6)
splitArrayV

[array([[1, 2, 3, 4, 5]]),
 array([[ 2,  4,  6,  8, 10]]),
 array([[ 3,  6,  9, 12, 15]]),
 array([[187, 158, 104, 121, 143]]),
 array([[198, 125, 255, 255, 147]]),
 array([[209, 134, 255,  97, 182]])]

In [67]:
#join 3 arrays horizontally
joinedArray3H=numpy.hstack((myArray, img_gray, myArray))
print(joinedArray3H)

[[  1   2   3   4   5 187 158 104 121 143   1   2   3   4   5]
 [  2   4   6   8  10 198 125 255 255 147   2   4   6   8  10]
 [  3   6   9  12  15 209 134 255  97 182   3   6   9  12  15]]


In [68]:
#join 3 arrays vertically
joinedArray3V=numpy.vstack((myArray, img_gray, myArray))
print(joinedArray3V)

[[  1   2   3   4   5]
 [  2   4   6   8  10]
 [  3   6   9  12  15]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [  1   2   3   4   5]
 [  2   4   6   8  10]
 [  3   6   9  12  15]]


[array([[ 1,  2,  3,  4,  5],
        [ 2,  4,  6,  8, 10],
        [ 3,  6,  9, 12, 15]]),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]])]

[array([[ 1,  2,  3,  4,  5],
        [ 2,  4,  6,  8, 10],
        [ 3,  6,  9, 12, 15]]),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]])]